/**
 * Bindings come from `worker-configuration.d.ts`, generated by
 * `npm run cf-typegen` from wrangler.jsonc. Do not hand-maintain them here --
 * a hand-written copy drifts from the config silently.
 *
 * Secrets are declared below because wrangler cannot know them: they are set
 * with `wrangler secret put` and never appear in the config file. All are
 * optional, so a missing secret is a typed, handled condition rather than a
 * runtime surprise (see docs/04-operations.md §3).
 */
declare global {
  namespace Cloudflare {
    interface Env {
      BETTER_AUTH_SECRET?: string;
      GOOGLE_CLIENT_ID?: string;
      GOOGLE_CLIENT_SECRET?: string;
      RESEND_API_KEY?: string;
      EMAIL_FROM?: string;
      FINNHUB_API_KEY?: string;
      ONESIGNAL_APP_ID?: string;
      ONESIGNAL_REST_API_KEY?: string;
    }
  }
}

export type Env = Cloudflare.Env;
