#!/usr/bin/env node
/**
 * Generates a development wrangler config from the real one, with `routes`
 * removed.
 *
 * Why this exists: `wrangler dev` simulates the custom domain declared in
 * `routes`, so the Worker sees `Host`/`Origin: stockalarm.torproduction.com`
 * even while you are browsing 127.0.0.1. That single fact has now caused two
 * bugs that were invisible to curl and only appeared in a browser:
 *
 *   - session cookies issued `Secure` over http, which browsers drop
 *     silently, so sign-in appeared to succeed and left no session;
 *   - Better Auth's CSRF check rejecting every sign-in with 403, so the login
 *     form showed FORBIDDEN.
 *
 * Both were worked around before. This removes the cause instead.
 *
 * The config is DERIVED rather than hand-maintained: a second checked-in
 * wrangler file would drift from the first the moment a binding is added, and
 * the drift would show up as a confusing runtime failure rather than an error.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(root, 'wrangler.jsonc');
const OUTPUT = join(root, '.wrangler.dev.json');

/**
 * Strips comments from JSONC.
 *
 * String-aware on purpose: a naive `//` strip mangles any value containing a
 * URL, and this file is full of them.
 */
export function stripJsonComments(input) {
  let out = '';
  let inString = false;
  let inLine = false;
  let inBlock = false;

  for (let i = 0; i < input.length; i += 1) {
    const ch = input[i];
    const next = input[i + 1];

    if (inLine) {
      if (ch === '\n') {
        inLine = false;
        out += ch;
      }
      continue;
    }

    if (inBlock) {
      if (ch === '*' && next === '/') {
        inBlock = false;
        i += 1;
      }
      continue;
    }

    if (inString) {
      out += ch;
      if (ch === '\\') {
        out += next ?? '';
        i += 1;
      } else if (ch === '"') {
        inString = false;
      }
      continue;
    }

    if (ch === '"') {
      inString = true;
      out += ch;
      continue;
    }
    if (ch === '/' && next === '/') {
      inLine = true;
      i += 1;
      continue;
    }
    if (ch === '/' && next === '*') {
      inBlock = true;
      i += 1;
      continue;
    }

    out += ch;
  }

  // Trailing commas are legal in JSONC and not in JSON.
  return out.replace(/,(\s*[}\]])/g, '$1');
}

const config = JSON.parse(stripJsonComments(readFileSync(SOURCE, 'utf8')));

delete config.routes;

// The name is deliberately NOT changed. Local D1 and KV state is keyed by it,
// and `wrangler d1 execute --local` resolves the name from wrangler.jsonc --
// so renaming here would point the test helpers at a different database than
// the dev server writes to. That is precisely the kind of silent divergence
// this script exists to avoid.

writeFileSync(
  OUTPUT,
  `${JSON.stringify(
    {
      _generated:
        'Generated by scripts/dev-config.mjs from wrangler.jsonc. Do not edit; do not commit.',
      ...config,
    },
    null,
    2,
  )}\n`,
);

console.log(`dev config written to ${OUTPUT} (routes removed)`);
